### ISSUE TITLE
Can´t use the plugin 

### ISSUE THREAD

**Issue by kripors** [abhinaba1080/protractor-react-selector#2]
I installed the plugin on my machine, but when I try to use it I get the error "    TypeError: by.ReactSelector is not a function " , can you help me ?

**Comment by abhinaba-ghosh** [comment]
can you share some sample codes? You can share a sample repo as well.

**Comment by kripors** [comment]
sure . here is the repo https://github.com/kripors/mobile, can you help me to fix this to use your plugin?
thanks

**Comment by kripors** [comment]
do you use skype ? maybe we can talk there . my skype is kripors@gmail.com

**Comment by abhinaba-ghosh** [comment]
@kripors : 

I am seeing the package is not mentioned in your package.json file. You need to create your own package.json file and then download the protractor-react-selector binaries by executing below command:

npm install --save protractor-react-selector 

please follow the blog for the complete setup : https://medium.com/@abhinabaghosh.1994/test-your-react-app-efficiently-with-protractor-b8406db9148f

let me know if this solves your issue. We can have a skype call if needed.
