### ISSUE TITLE
Javascript error: Could not find instance of React in given element.

### ISSUE THREAD

**Issue by jlehett** [abhinaba1080/protractor-react-selector#5]
Receiving this error on a BitBucket pipeline when using `await browser.wait(protractor.ExpectedConditions.presenceOf(_REACT_COMPONENT_SELECTOR_))`

```
Failed: javascript error: Could not find instance of React in given element
        (Session info: headless chrome=81.0.4044.138)
        (Driver info: chromedriver=81.0.4044.69
```
This failure occurs instantly as opposed to waiting for the timeout value and returning a Script timeout error when the React component could not be found.

Runs fine on my own local server, but seems to break on a BitBucket pipeline. Any suggestions on what this error could mean?

**Comment by abhinaba-ghosh** [comment]
Hi @jlehett, Thanks for trying out protractor-react-selector. 

It seems that the react selector is getting consumed by the react root you provided. Can you share some more info:

1. the protractor-react-selector version you are using?
2. how you are calling ```await browser.waitForReact()``` script?
3. What is the react root of your web app?

Would you mind sharing a sample repo, so that I can deeply look into this? This is something very interesting.

**Comment by jlehett** [comment]
Hi @abhinaba-ghosh,

Currently using version 2.2.2 -- unfortunately I am not that familiar with React, so I can't say for sure what the root is, but it should match up with the sample repo I've created: [Repo](https://github.com/jlehett/Sample-React-App)

Again, not very familiar with it, and currently using a different set up of npm start, so I'm not entire sure it will run. But the structure and code is very similar between them.

It's very puzzling to me that the e2e tests run perfectly for me on a local machine, but when put through BitBucket pipelines, it returns that error message.

**Comment by jlehett** [comment]
It seems as though the issue was being caused by the React root component not containing the "_reactRootContainer" property for some reason on BitBucket, but it did on localhost.

I believe this is unrelated to protractor-react-selector, so I believe this issue can be closed. Sorry for the confusion.

**Comment by abhinaba-ghosh** [comment]
Hi @jlehett , I am glad that protractor-react-selector actually working as expected. Best of luck in your automation journey. By any chance, if protractor-react-selector made an impact in your org, choose to [sponsor](https://www.patreon.com/user?u=32109749&fan_landing=true) the project for new features along the road.

**Comment by kennydifiore** [comment]
@abhinaba-ghosh 
1. We're using v2.2.2 of protractor-react-selector
2. We're using jasmine testing framework with protractor, and calling browser.waitForReact() like so:
```
const WAIT_FOR_REACT_TIMEOUT = 50000;
describe('Application', () => {
    beforeEach(async () => {
        await browser.get(browser.baseUrl);
        await browser.waitForReact(WAIT_FOR_REACT_TIMEOUT);
    });

   //... it() tests that use by.react() element selector
});
```
3. The react root is `#root`

browser.waitForReact is not waiting for the full timeout to elapse before bailing out.

**Comment by abhinaba-ghosh** [comment]
Hi @kennydifiore , thanks that you asked this question. is it possible to create a separate ticket? Please add the ```protractor.conf``` file as well. if you think, creating a sample repo makes life easy for debugging, please create one and share. I will definitely have a quick look. 

Thanks for understanding.

**Comment by abhinaba-ghosh** [comment]
Hi, i suggest to move to new version V2.2.3 for more robust ```wairForReact``` mechanism.
